import type { RunDetail, RunSummary } from "@/lib/contracts";

export const runs: RunSummary[] = [
  {
    id: "run_prd_0187",
    title: "大学生 AI 学习平台 PRD",
    status: "succeeded",
    startedAt: "今天 09:42",
    duration: "2m 18s",
    quality: 91.6,
    inputTokens: 18420,
    outputTokens: 6830,
  },
  {
    id: "run_prd_0186",
    title: "跨境团队知识中台",
    status: "blocked",
    startedAt: "今天 08:15",
    duration: "4m 02s",
    quality: 78.4,
    inputTokens: 26910,
    outputTokens: 9150,
  },
  {
    id: "run_prd_0185",
    title: "连锁门店排班助手",
    status: "succeeded",
    startedAt: "昨天 18:31",
    duration: "1m 54s",
    quality: 88.9,
    inputTokens: 15770,
    outputTokens: 5920,
  },
  {
    id: "run_prd_0184",
    title: "保险理赔材料预审",
    status: "failed",
    startedAt: "昨天 16:07",
    duration: "48s",
    quality: null,
    inputTokens: 5340,
    outputTokens: 890,
  },
];

export const runDetail: RunDetail = {
  ...runs[0],
  request: "设计一个面向大学生的 AI 学习平台，并生成可评审的完整 PRD。",
  project: "Nexus PRD / Education",
  iteration: 1,
  tasks: [
    {
      id: "requirements",
      title: "需求澄清与边界",
      agent: "Product Manager",
      status: "succeeded",
      duration: "19s",
      skills: ["requirement-analysis"],
      dependencies: [],
    },
    {
      id: "market",
      title: "市场与竞品研究",
      agent: "Researcher",
      status: "succeeded",
      duration: "43s",
      skills: ["market-research", "competitor-analysis"],
      dependencies: ["requirements"],
    },
    {
      id: "experience",
      title: "用户流程设计",
      agent: "UX Designer",
      status: "succeeded",
      duration: "31s",
      skills: ["user-flow-design"],
      dependencies: ["requirements"],
    },
    {
      id: "architecture",
      title: "技术可行性评估",
      agent: "Architect",
      status: "succeeded",
      duration: "27s",
      skills: ["architecture-review"],
      dependencies: ["requirements"],
    },
    {
      id: "write",
      title: "PRD 汇总与写作",
      agent: "Writer",
      status: "succeeded",
      duration: "36s",
      skills: ["prd-writing"],
      dependencies: ["market", "experience", "architecture"],
    },
    {
      id: "review",
      title: "结构化质量评审",
      agent: "Reviewer",
      status: "succeeded",
      duration: "22s",
      skills: ["quality-review"],
      dependencies: ["write"],
    },
  ],
  routing: [
    {
      skillId: "requirement-analysis",
      score: 0.943,
      selected: true,
      reasons: ["领域匹配 product", "命中必需能力 requirements", "混合检索排名 #1"],
      instructionTokens: 418,
    },
    {
      skillId: "market-research",
      score: 0.891,
      selected: true,
      reasons: ["意图包含市场验证", "Researcher 工具权限兼容", "Token 预算内"],
      instructionTokens: 366,
    },
    {
      skillId: "competitor-analysis",
      score: 0.846,
      selected: true,
      reasons: ["竞品证据可提升 PRD 完整性", "与主 Skill 互补"],
      instructionTokens: 392,
    },
    {
      skillId: "generic-brainstorming",
      score: 0.428,
      selected: false,
      reasons: ["缺少领域专用约束", "预算裁剪后排除"],
      instructionTokens: 611,
    },
  ],
  review: {
    清晰度: 93,
    完整性: 92,
    可行性: 89,
    一致性: 91,
    证据覆盖: 93,
  },
  artifacts: [
    { name: "PRD.md", mediaType: "text/markdown", size: "28.4 KB" },
    { name: "run-record.json", mediaType: "application/json", size: "14.7 KB" },
  ],
};
