import assert from "node:assert/strict";

// PLAYWRIGHT_MODULE can point to an existing runner installation.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || "playwright");
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
const failures = [];
page.on("pageerror", (error) => failures.push(error.message));
page.on("dialog", (dialog) => dialog.accept());
const base = process.env.STUDIO_TEST_URL || "http://127.0.0.1:13123";
try {
  await page.goto(`${base}/studio`);
  await page.getByRole("textbox", { name: "工作区名称" }).fill("浏览器验收工作区");
  await page.getByRole("button", { name: "创建工作区", exact: true }).click();
  await page.waitForURL(/workspace=/);
  const rail = page.getByRole("navigation", { name: "工作区视图" });
  assert.equal(await rail.getByRole("button", { name: "需求文档", exact: true }).count(), 0);
  await rail.getByRole("button", { name: "Agent", exact: true }).click();
  await page.getByRole("list", { name: "Agent 插件" }).getByRole("button", { name: /PRD 编写/ }).click();
  await page.getByRole("article", { name: "PRD 编写 Agent 详情" }).getByRole("button", { name: "运行 / 打开工作台" }).click();
  const editor = page.getByRole("textbox", { name: "PRD 正文", exact: true });
  await page.getByRole("button", { name: "需求简报", exact: true }).click();
  await page.locator("#studio-title").fill("浏览器验收 PRD");
  await page.getByRole("button", { name: "收起需求简报", exact: true }).click();
  await editor.fill("# 手工编写\n这个草稿需要保留。");
  await editor.press("Control+s");
  await page.getByRole("status").filter({ hasText: "已保存 r2" }).waitFor();
  await editor.fill("# 尚未保存的浏览器草稿");
  await page.reload();
  await editor.waitFor();
  assert.equal(await editor.inputValue(), "# 尚未保存的浏览器草稿");
  await editor.press("Control+s");
  await page.getByRole("status").filter({ hasText: "已保存 r3" }).waitFor();
  await page.getByRole("textbox", { name: "给 Agent 的指令" }).fill("编写需求草稿");
  await page.getByRole("button", { name: "发送（保存上下文并生成提案）" }).click();
  const apply = page.getByRole("button", { name: "应用到原资源 r3" });
  await apply.waitFor({ timeout: 15000 });
  assert.equal(await editor.inputValue(), "# 尚未保存的浏览器草稿");
  await page.getByRole("button", { name: "查看工作流", exact: true }).click();
  const workflow = page.getByRole("article", { name: "Agent 工作流记录" });
  await workflow.getByRole("status").filter({ hasText: "7 / 7 个阶段完成" }).waitFor();
  assert.equal(await workflow.locator("[data-flow-node]").count(), 7);
  const reviewNode = workflow.getByRole("button", { name: "质量评审 · 已完成", exact: true });
  await reviewNode.focus();
  await page.keyboard.press("Enter");
  const dialog = page.getByRole("dialog", { name: "质量评审", exact: true });
  await dialog.waitFor();
  assert.match(await dialog.textContent(), /reviewer.*1.0.0/s);
  assert.match(await dialog.textContent(), /请人工核验范围与验收要求/);
  await page.keyboard.press("Escape");
  await dialog.waitFor({ state: "hidden" });
  assert.equal(await reviewNode.evaluate((element) => document.activeElement === element), true);
  await page.screenshot({ path: "/tmp/nexus-agent-workflow-browser.png", fullPage: true });
  await page.reload();
  await workflow.getByRole("status").filter({ hasText: "7 / 7 个阶段完成" }).waitFor();
  await workflow.getByRole("button", { name: "返回原资源", exact: true }).click();
  await page.getByRole("button", { name: "任务", exact: true }).click();
  assert.equal(await editor.inputValue(), "# 尚未保存的浏览器草稿");
  await apply.click();
  await page.waitForFunction(() => document.querySelector('textarea[aria-label="PRD 正文"]')?.value.includes("Agent 草稿"));
  // Clarification changes only the brief, and only after approval.
  const originalContent = await editor.inputValue();
  await page.getByRole("button", { name: "需求简报", exact: true }).click();
  await page.getByRole("combobox", { name: "Agent 能力" }).selectOption("clarify");
  await page.getByRole("textbox", { name: "给 Agent 的指令" }).fill("澄清目标用户");
  await page.getByRole("button", { name: "发送（保存上下文并生成提案）" }).click();
  await page.getByRole("button", { name: "应用到原资源 r4" }).waitFor();
  assert.equal(await page.locator("#studio-audience").inputValue(), "");
  await page.getByRole("button", { name: "应用到原资源 r4" }).click();
  await page.waitForFunction(() => document.querySelector("#studio-audience")?.value === "设计师与产品经理");
  assert.equal(await editor.inputValue(), originalContent);
  await page.getByRole("button", { name: "收起需求简报", exact: true }).click();
  await page.getByRole("button", { name: "资源", exact: true }).click();
  await page.getByRole("button", { name: "文件", exact: true }).click();
  await page.getByRole("button", { name: "新建原型设计", exact: true }).click();
  await page.getByRole("button", { name: "代码", exact: true }).click();
  const code = page.getByRole("textbox", { name: "结构化原型 JSON" });
  await code.fill('{"unfinished":');
  await page.reload();
  await page.getByRole("button", { name: "代码", exact: true }).click();
  assert.equal(await code.inputValue(), '{"unfinished":');
  await page.getByRole("button", { name: "还原", exact: true }).click();
  const design = JSON.parse(await code.inputValue());
  design.content = [{ type: "Heading", props: { id: "browser-heading", label: "欢迎使用", detail: "", target: "", tone: "green", left: [], right: [] } }];
  await code.fill(JSON.stringify(design, null, 2));
  await page.getByRole("button", { name: "应用代码", exact: true }).click();
  assert.equal(await page.evaluate(() => Object.keys(localStorage).some((key) => key.startsWith("nexus:drafts:v1:nexus-studio%3Acode"))), false);
  await page.getByRole("combobox", { name: "Agent 能力" }).selectOption("component");
  await page.getByRole("textbox", { name: "给 Agent 的指令" }).fill("修改标题");
  await page.getByRole("button", { name: "发送（保存上下文并生成提案）" }).click();
  await page.getByRole("alert").filter({ hasText: "请先在原型画布中选择组件" }).waitFor();
  await page.getByRole("button", { name: "设计", exact: true }).click();
  await page.getByRole("heading", { name: "欢迎使用", exact: true }).click();
  await page.getByRole("button", { name: "发送（保存上下文并生成提案）" }).click();
  await page.getByText("仅修改所选组件", { exact: true }).waitFor();
  const componentTask = page.locator("section").filter({ has: page.getByText("仅修改所选组件", { exact: true }) });
  await componentTask.getByText("本次调用范围", { exact: true }).click();
  assert.match(await componentTask.textContent(), /browser-heading/);
  await componentTask.getByRole("button", { name: /应用到原资源/ }).click();
  await page.getByRole("heading", { name: "Agent 修改的标题", exact: true }).waitFor();
  await page.getByRole("button", { name: "代码", exact: true }).click();
  assert.equal(JSON.parse(await code.inputValue()).content[0].props.label, "Agent 修改的标题");
  await page.getByRole("button", { name: "页面", exact: true }).click();
  await page.getByRole("textbox", { name: "页面与交互说明", exact: true }).fill("浏览器用户可以查看欢迎信息。");
  await page.getByLabel("原型操作", { exact: true }).click();
  await page.getByRole("button", { name: "确认并交给 PRD 编写", exact: true }).click();
  await page.getByRole("button", { name: "交给 浏览器验收 PRD", exact: true }).waitFor({ timeout: 20000 });
  await page.getByRole("button", { name: "交给 浏览器验收 PRD", exact: true }).click();
  await page.getByRole("button", { name: "确认并应用", exact: true }).click();
  await editor.waitFor();
  assert.match(await editor.inputValue(), /studio-source:/);
  const other = await browser.newPage();
  await other.goto(page.url());
  const otherEditor = other.getByRole("textbox", { name: "PRD 正文", exact: true });
  // A new independent tab has no inherited editor selection; open the resource explicitly.
  await other.getByRole("button", { name: /浏览器验收 PRD/ }).first().click();
  await otherEditor.fill("# 另一个窗口的草稿");
  await editor.fill("# 第一个窗口的草稿");
  await other.reload();
  await otherEditor.waitFor();
  assert.equal(await otherEditor.inputValue(), "# 另一个窗口的草稿");
  await otherEditor.press("Control+s");
  await other.getByRole("status").filter({ hasText: "已保存" }).waitFor();
  await editor.press("Control+s");
  await page.getByRole("alert").filter({ hasText: "REVISION_CONFLICT" }).waitFor();
  assert.equal(await editor.inputValue(), "# 第一个窗口的草稿");
  await other.close();
  // Closed views release editor components; persisted sessions restore the draft.
  await page.getByRole("button", { name: /关闭浏览器验收 PRD/ }).click();
  await page.keyboard.press("Control+Shift+t");
  await editor.waitFor();
  assert.equal(await editor.inputValue(), "# 第一个窗口的草稿");
  await page.getByRole("button", { name: "插件", exact: true }).click();
  const prdPlugin = page.locator("section").filter({ has: page.locator("strong", { hasText: "PRD 编写" }) });
  await prdPlugin.getByRole("button", { name: "停用", exact: true }).click();
  await editor.waitFor({ state: "hidden" });
  await prdPlugin.getByRole("button", { name: "启用", exact: true }).click();
  await editor.waitFor();
  assert.equal(await editor.inputValue(), "# 第一个窗口的草稿");
  const prototypePlugin = page.locator("section").filter({ has: page.locator("strong", { hasText: "原型设计" }) });
  await prototypePlugin.getByRole("button", { name: "停用", exact: true }).click();
  await prdPlugin.getByRole("button", { name: "停用", exact: true }).click();
  await page.getByRole("button", { name: "资源", exact: true }).click();
  assert.equal(await page.getByRole("button", { name: "新建PRD 编写", exact: true }).count(), 0);
  await page.getByRole("button", { name: "专注全屏", exact: true }).click();
  await page.getByRole("button", { name: "退出专注", exact: true }).click();

  await page.getByRole("button", { name: "插件", exact: true }).click();
  const notes = page.locator("section").filter({ has: page.locator("strong", { hasText: "示例便签" }) });
  await notes.getByRole("button", { name: "启用", exact: true }).click();
  await rail.getByRole("button", { name: "Agent", exact: true }).click();
  await page.getByRole("list", { name: "Agent 插件" }).getByRole("button", { name: /示例便签/ }).click();
  await page.getByRole("article", { name: "示例便签 Agent 详情" }).getByRole("button", { name: "运行 / 打开工作台" }).click();
  const note = page.getByRole("textbox", { name: "便签正文", exact: true });
  await note.fill("第三插件的独立内容");
  await note.press("Control+s");
  await page.getByRole("status").filter({ hasText: "已保存 r2" }).waitFor();
  await rail.getByRole("button", { name: "资源", exact: true }).click();
  await page.getByRole("button", { name: /便签列表/, exact: false }).click();
  await page.getByRole("region", { name: "便签资源" }).getByRole("button", { name: "未命名便签 · r2", exact: true }).waitFor();
  await page.getByRole("textbox", { name: "给 Agent 的指令" }).fill("整理便签");
  await page.getByRole("button", { name: "发送（保存上下文并生成提案）" }).click();
  await page.getByRole("button", { name: "应用到原资源 r2" }).click();
  await page.waitForFunction(() => document.querySelector('textarea[maxlength="20000"]')?.value === "整理后的便签");
  await page.screenshot({ path: "/tmp/nexus-plugin-workspace-browser.png", fullPage: true });
  assert.deepEqual(failures, []);
  console.log("PASS: create/save, draft recovery, workflow graph/details/keyboard/reload, Agent approval, clarification, scoped component suggestions, prototype JSON recovery, screenshot handoff, two-window isolation, CAS, disable/re-enable, focus and third plugin editor/view/Agent; real API + deterministic model");
} finally { await browser.close(); }
